// Assuming the logged-in Main Authority is: Maharashtra Pollution Control Board (MPCB)
export const mainAuthDocsData = [
  {
    id: 'DOC-MPCB-001',
    name: 'Consent to Establish (CTE) - Orange Category',
    category: 'Industrial Clearance',
    slaDays: 30,
    baseFee: '₹15,000',
    status: 'ACTIVE', // 'ACTIVE' | 'PAUSED' | 'DRAFT'
    totalApplications: 1245,
    lastUpdated: '12 Aug 2026',
    description: 'Initial permission required before setting up an industry that falls under the orange pollution category.',
  },
  {
    id: 'DOC-MPCB-002',
    name: 'Consent to Operate (CTO) - Red Category',
    category: 'Industrial Clearance',
    slaDays: 45,
    baseFee: '₹25,000',
    status: 'ACTIVE',
    totalApplications: 890,
    lastUpdated: '05 Sep 2026',
    description: 'Mandatory operational clearance for highly polluting industries after construction is complete.',
  },
  {
    id: 'DOC-MPCB-003',
    name: 'Hazardous Waste Authorization (Form 1)',
    category: 'Waste Management',
    slaDays: 21,
    baseFee: '₹10,000',
    status: 'ACTIVE',
    totalApplications: 412,
    lastUpdated: '20 Jul 2026',
    description: 'Approval for the collection, storage, and disposal of industrial hazardous waste.',
  },
  {
    id: 'DOC-MPCB-004',
    name: 'E-Waste Recycling Clearance',
    category: 'Waste Management',
    slaDays: 60,
    baseFee: '₹5,000',
    status: 'PAUSED',
    totalApplications: 85,
    lastUpdated: '01 Sep 2026',
    description: 'License for facilities engaging in the dismantling and recycling of electronic waste.',
  },
  {
    id: 'DOC-MPCB-005',
    name: 'Battery Waste Management Registration',
    category: 'Green Initiative',
    slaDays: 15,
    baseFee: 'Free',
    status: 'DRAFT',
    totalApplications: 0,
    lastUpdated: '10 Sep 2026',
    description: 'New scheme for registering dealers and recyclers of lead-acid and lithium-ion batteries.',
  },
];