import ApprovalCatalog from '../models/ApprovalCatalog.js';

export const initialMasterApprovals = [
  {
    id: 'appr-01',
    title: 'Consent to Establish (CTE) — Pollution Board',
    category: 'Environment & Pollution',
    department: 'Maharashtra Pollution Control Board (MPCB)',
    authority: 'Maharashtra Pollution Control Board (MPCB)',
    authorityBody: 'Maharashtra Pollution Control Board (MPCB)',
    district: 'ALL',
    slaDays: 45,
    fee: 15000,
    description: 'Mandatory environmental clearance before breaking ground or erecting civil machinery under Water Act 1974 & Air Act 1981.',
    requiresInspection: true,
    inspectionTiming: 'Before Approval Issuance',
    status: 'ACTIVE',
    type: 'CLEARANCE',
    requiredDocs: [
      { documentName: 'Site Plan / Layout', isMandatory: true, category: 'LAND' },
      { documentName: 'Identity Proof (Aadhaar/PAN)', isMandatory: true, category: 'IDENTITY' },
      { documentName: 'Process Flow Diagram', isMandatory: true, category: 'TECHNICAL' },
      { documentName: 'Effluent Treatment Plant (ETP) Proposal', isMandatory: false, category: 'ENVIRONMENT' },
    ],
  },
  {
    id: 'appr-02',
    title: 'Provisional Fire Safety NOC',
    category: 'Fire Safety',
    department: 'Maharashtra Fire Services',
    authority: 'Maharashtra Fire Services / MIDC Fire Wing',
    authorityBody: 'Maharashtra Fire Services / MIDC Fire Wing',
    district: 'ALL',
    slaDays: 21,
    fee: 7500,
    description: 'Mandatory fire evacuation and hydrant layout approval before building plan sanction and construction.',
    requiresInspection: true,
    inspectionTiming: 'Before Approval Issuance',
    status: 'ACTIVE',
    type: 'CLEARANCE',
    requiredDocs: [
      { documentName: 'Site Plan / Layout', isMandatory: true, category: 'LAND' },
      { documentName: 'Building Elevation Drawings', isMandatory: true, category: 'TECHNICAL' },
      { documentName: 'Fire Hydrant Layout', isMandatory: true, category: 'TECHNICAL' },
    ],
  },
  {
    id: 'appr-03',
    title: 'Factory Building Plan Approval',
    category: 'Land & Town Planning',
    department: 'Town Planning & Municipal Corporation',
    authority: 'Town Planning & Municipal Corporation',
    authorityBody: 'Town Planning & Municipal Corporation',
    district: 'ALL',
    slaDays: 30,
    fee: 20000,
    description: 'Structural stability, setbacks, and FSI/FAR compliance sanction for industrial sheds and civil structures.',
    requiresInspection: false,
    inspectionTiming: 'Desk Review',
    status: 'ACTIVE',
    type: 'CLEARANCE',
    requiredDocs: [
      { documentName: 'Site Plan / Layout', isMandatory: true, category: 'LAND' },
      { documentName: 'Structural Engineer Certificate', isMandatory: true, category: 'LEGAL' },
      { documentName: '7/12 Land Extract', isMandatory: true, category: 'LAND' },
    ],
  },
  {
    id: 'appr-04',
    title: 'FSSAI State Manufacturing License',
    category: 'Food Safety & Hygiene',
    department: 'Food Safety and Standards Authority of India (FSSAI)',
    authority: 'Food Safety and Standards Authority of India (FSSAI)',
    authorityBody: 'Food Safety and Standards Authority of India (FSSAI)',
    district: 'ALL',
    slaDays: 30,
    fee: 5000,
    description: 'Statutory food manufacturing and packaging license under Food Safety and Standards Act, 2006.',
    requiresInspection: true,
    inspectionTiming: 'Post Commencement',
    status: 'ACTIVE',
    type: 'CLEARANCE',
    requiredDocs: [
      { documentName: 'Identity Proof (Aadhaar/PAN)', isMandatory: true, category: 'IDENTITY' },
      { documentName: 'Water Quality Test Report', isMandatory: true, category: 'TECHNICAL' },
      { documentName: 'List of Machinery', isMandatory: true, category: 'TECHNICAL' },
    ],
  },
  {
    id: 'appr-05',
    title: 'Factory Registration & License (Form 1)',
    category: 'Labor & Factory Safety',
    department: 'Directorate of Industrial Safety & Health (DISH)',
    authority: 'Directorate of Industrial Safety & Health (DISH)',
    authorityBody: 'Directorate of Industrial Safety & Health (DISH)',
    district: 'ALL',
    slaDays: 30,
    fee: 4500,
    description: 'Worker occupational safety, ventilation, and machinery guarding license under Factories Act, 1948.',
    requiresInspection: true,
    inspectionTiming: 'Before Approval Issuance',
    status: 'ACTIVE',
    type: 'CLEARANCE',
    requiredDocs: [
      { documentName: 'Identity Proof (Aadhaar/PAN)', isMandatory: true, category: 'IDENTITY' },
      { documentName: 'List of Machinery', isMandatory: true, category: 'TECHNICAL' },
      { documentName: 'List of Directors/Partners', isMandatory: true, category: 'LEGAL' },
    ],
  },
  {
    id: 'appr-06',
    title: 'MSEDCL High-Tension (HT) Power Sanction',
    category: 'Power & Energy',
    department: 'Maharashtra State Electricity Distribution Co. Ltd. (MSEDCL)',
    authority: 'MSEDCL & Chief Electrical Inspectorate (CEI)',
    authorityBody: 'MSEDCL',
    district: 'ALL',
    slaDays: 30,
    fee: 12000,
    description: 'Dedicated high-voltage HT substation transformer load sanction and CEI earth pit approval for loads > 70 HP.',
    requiresInspection: true,
    inspectionTiming: 'Before Approval Issuance',
    status: 'ACTIVE',
    type: 'CLEARANCE',
    requiredDocs: [
      { documentName: 'Electrical Single Line Diagram (SLD)', isMandatory: true, category: 'TECHNICAL' },
      { documentName: 'CEI Earthing Test Report', isMandatory: true, category: 'TECHNICAL' },
      { documentName: 'Connected Load List', isMandatory: true, category: 'TECHNICAL' },
    ],
  },
  {
    id: 'appr-07',
    title: 'Diesel Generator (DG Set) Installation Sanction',
    category: 'Power & Safety',
    department: 'Chief Electrical Inspectorate (CEI)',
    authority: 'Chief Electrical Inspectorate (CEI)',
    authorityBody: 'Chief Electrical Inspectorate (CEI)',
    district: 'ALL',
    slaDays: 15,
    fee: 3500,
    description: 'Form C approval, acoustic noise enclosure certification, and emergency backup generator sanction.',
    requiresInspection: true,
    inspectionTiming: 'Before Approval Issuance',
    status: 'ACTIVE',
    type: 'CLEARANCE',
    requiredDocs: [
      { documentName: 'DG Acoustic Enclosure Certificate', isMandatory: true, category: 'TECHNICAL' },
      { documentName: 'Electrical Contractor Certificate', isMandatory: true, category: 'LEGAL' },
    ],
  },
  {
    id: 'appr-08',
    title: 'Boiler / Pressure Vessel Registration & Fitness',
    category: 'Boiler & Steam Safety',
    department: 'Directorate of Steam Boilers',
    authority: 'Directorate of Steam Boilers',
    authorityBody: 'Directorate of Steam Boilers',
    district: 'ALL',
    slaDays: 30,
    fee: 8000,
    description: 'Hydrostatic pressure testing and certified IBR operator validation under the Indian Boilers Act, 1923.',
    requiresInspection: true,
    inspectionTiming: 'Before Approval Issuance',
    status: 'ACTIVE',
    type: 'CLEARANCE',
    requiredDocs: [
      { documentName: 'IBR Manufacturer Certificate', isMandatory: true, category: 'TECHNICAL' },
      { documentName: 'Boiler Operator Competency Card', isMandatory: true, category: 'LEGAL' },
    ],
  },
  {
    id: 'appr-09',
    title: 'Hazardous Waste Management Authorization (Form 1)',
    category: 'Environment & Pollution',
    department: 'Maharashtra Pollution Control Board (MPCB)',
    authority: 'Maharashtra Pollution Control Board (MPCB)',
    authorityBody: 'Maharashtra Pollution Control Board (MPCB)',
    district: 'ALL',
    slaDays: 45,
    fee: 10000,
    description: 'Authorization for handling, storage, and disposal of hazardous/chemical waste under HWM Rules 2016.',
    requiresInspection: true,
    inspectionTiming: 'Before Approval Issuance',
    status: 'ACTIVE',
    type: 'CLEARANCE',
    requiredDocs: [
      { documentName: 'Hazardous Waste Storage Layout', isMandatory: true, category: 'TECHNICAL' },
      { documentName: 'Common Hazardous Waste TSDF Membership', isMandatory: true, category: 'ENVIRONMENT' },
    ],
  },
  {
    id: 'DOC-MPCB-001',
    title: 'Consent to Establish (CTE) - Orange Category',
    category: 'Industrial Clearance',
    department: 'Maharashtra Pollution Control Board (MPCB)',
    authority: 'Maharashtra Pollution Control Board (MPCB)',
    authorityBody: 'Maharashtra Pollution Control Board (MPCB)',
    district: 'Aurangabad',
    slaDays: 30,
    fee: 15000,
    description: 'Consent to Establish for Orange Category food/dairy processing unit.',
    requiresInspection: true,
    inspectionTiming: 'Before Approval Issuance',
    status: 'ACTIVE',
    type: 'CLEARANCE',
    requiredDocs: [
      { documentName: 'Site Plan', isMandatory: true, category: 'LAND' },
      { documentName: 'Identity Proof', isMandatory: true, category: 'IDENTITY' },
      { documentName: 'Process Flow Diagram', isMandatory: true, category: 'TECHNICAL' },
    ],
  },
];

export const seedApprovalsCatalog = async () => {
  try {
    for (const item of initialMasterApprovals) {
      await ApprovalCatalog.findOneAndUpdate(
        { id: item.id },
        { $set: item },
        { upsert: true, returnDocument: 'after' }
      );
    }
    console.log(`[Seed] Approval catalog verified (${initialMasterApprovals.length} master clearances active).`);
  } catch (error) {
    console.error('[Seed Error] Failed to seed approval catalog:', error.message);
  }
};

export default seedApprovalsCatalog;
