export const initialMainAuthRequestsData = [
  {
    requestId: 'CENTRAL-REQ-2026-901',
    appliedDate: '2026-09-01',
    requestedDocName: 'State Environmental Impact Clearance (Category B1)',
    clearanceLevel: 'APEX_STATE_CLEARANCE',
    forwardedBy: 'MPCB Sub-Regional Desk Raigad',
    enterprise: {
      name: 'Godavari Mega Petrochem & Polymers SEZ Ltd',
      type: 'Heavy Petrochemical Refinery & Bulk Storage',
      ownerName: 'Vikramaditya Singhania',
      mobile: '+91 98110 44290',
      email: 'clearance@godavaripetrochem.in',
      plotLocation: 'Special Investment Region, Dighi Port Industrial Corridor',
      district: 'Raigad',
      capitalInvestmentInr: '₹ 450 Crores',
      connectedLoad: '12.5 MVA',
    },
    userDocs: [
      { id: 'cd-1', title: 'Comprehensive Environmental Impact Assessment (EIA).pdf', size: '14.2 MB', fileUrl: '#' },
      { id: 'cd-2', title: 'State Environmental Appraisal Committee (SEAC) Minutes.pdf', size: '3.8 MB', fileUrl: '#' },
      { id: 'cd-3', title: 'Public Hearing Proceedings & Collector Signoff.pdf', size: '5.1 MB', fileUrl: '#' },
      { id: 'cd-4', title: 'Zero Liquid Discharge (ZLD) Blueprint.pdf', size: '4.6 MB', fileUrl: '#' },
    ],
    scrutinyHistory: [
      { stage: 'Local Desk Scrutiny', status: 'RECOMMENDED', officer: 'S. K. Kulkarni (Raigad SRO)', date: '2026-08-20' },
      { stage: 'Field Environmental Inspection', status: 'PASSED', officer: 'Anand Patil (Field Tech Directorate)', date: '2026-08-28' },
      { stage: 'Apex Directorate Signoff', status: 'PENDING_APEX_DECISION', officer: 'Member Secretary / Principal Secretary', date: '2026-09-01' },
    ],
    status: 'PENDING_REVIEW', // 'PENDING_REVIEW' | 'APPROVED' | 'REJECTED'
    signedDocId: null,
    rejectionReason: null,
  },
  {
    requestId: 'CENTRAL-REQ-2026-884',
    appliedDate: '2026-08-26',
    requestedDocName: 'Major Accident Hazard (MAH) Factory Plan Sanction',
    clearanceLevel: 'CENTRAL_STATUTORY_SANCTION',
    forwardedBy: 'DISH Thane Divisional Directorate',
    enterprise: {
      name: 'Hindustan Specialty Gases & Cryogenics Pvt Ltd',
      type: 'Cryogenic Liquid Nitrogen & Hydrogen Bottling',
      ownerName: 'Dr. Ananya Mukherjee',
      mobile: '+91 98220 91823',
      email: 'regulatory@hsgases.com',
      plotLocation: 'Plot CP-88, Taloja Chemical Industrial Estate',
      district: 'Raigad',
      capitalInvestmentInr: '₹ 85 Crores',
      connectedLoad: '3.2 MVA',
    },
    userDocs: [
      { id: 'cd-11', title: 'On-Site Emergency Disaster Management Plan.pdf', size: '6.4 MB', fileUrl: '#' },
      { id: 'cd-12', title: 'PESO High Pressure Vessel Hydraulic Test Logs.pdf', size: '4.1 MB', fileUrl: '#' },
      { id: 'cd-13', title: 'Quantitative Risk Assessment (QRA) Modeling.pdf', size: '8.9 MB', fileUrl: '#' },
    ],
    scrutinyHistory: [
      { stage: 'District Safety Inspection', status: 'RECOMMENDED', officer: 'R. K. Verma (DISH Thane)', date: '2026-08-15' },
      { stage: 'Joint Chemical Hazard Directorate Scrutiny', status: 'PENDING_APEX_DECISION', officer: 'Chief Inspector of Factories (HQ)', date: '2026-08-26' },
    ],
    status: 'PENDING_REVIEW',
    signedDocId: null,
    rejectionReason: null,
  },
  {
    requestId: 'CENTRAL-REQ-2026-790',
    appliedDate: '2026-08-18',
    requestedDocName: 'Industrial Water Drawal Concurrence (> 500 KLD)',
    clearanceLevel: 'INTER_DEPARTMENTAL_CONCURRENCE',
    forwardedBy: 'MIDC Water Works Chief Engineer Office',
    enterprise: {
      name: 'Konkan Paper Pulp & Packaging Mills',
      type: 'Pulp Processing & Kraft Paper Mill',
      ownerName: 'Mahendra P. Gaikwad',
      mobile: '+91 99600 55120',
      email: 'm.gaikwad@konkanpaper.in',
      plotLocation: 'Plot K-10, Mahad MIDC Industrial Cluster',
      district: 'Raigad',
      capitalInvestmentInr: '₹ 120 Crores',
      connectedLoad: '4.8 MVA',
    },
    userDocs: [
      { id: 'cd-21', title: 'Savitri River Basin Water Balance Study.pdf', size: '5.5 MB', fileUrl: '#' },
      { id: 'cd-22', title: 'Tertiary Recycling & Effluent Reuse Report.pdf', size: '3.2 MB', fileUrl: '#' },
    ],
    scrutinyHistory: [
      { stage: 'Irrigation & River Basin Hydro Inspection', status: 'RECOMMENDED', officer: 'Executive Engineer, Water Resources', date: '2026-08-10' },
      { stage: 'State Water Sanction High Powered Committee', status: 'PENDING_APEX_DECISION', officer: 'Secretary, Water Resources & Industry', date: '2026-08-18' },
    ],
    status: 'PENDING_REVIEW',
    signedDocId: null,
    rejectionReason: null,
  },
];
