export const initialApprovalsList = [
  {
    id: 'appr-01',
    docName: 'Consent to Establish (CTE) — Pollution Board',
    authority: 'Maharashtra Pollution Control Board (MPCB)',
    fee: 15000,
    alreadyHave: false,
    uploadedFile: null,
    checkedForApply: false,
    tag: 'warning',
    aiReason: 'Because your factory falls in Orange Category with connected power above 100 HP, MPCB permission is mandatory before civil work or machinery fitting starts.',
    aiPoints: [
      'Submit Form CTE-1 on the MPCB online portal',
      'Attach factory layout, process flow, and effluent details',
      'Field inspection will be scheduled after document review',
      'Issued before any civil construction begins',
    ],
    requiredDocs: ['Site Plan / Layout', 'Identity Proof (Aadhaar/PAN)', 'Process Flow Diagram'],
  },
  {
    id: 'appr-02',
    docName: 'Provisional Fire Safety NOC',
    authority: 'Maharashtra Fire Services / MIDC Fire Wing',
    fee: 7500,
    alreadyHave: false,
    uploadedFile: null,
    checkedForApply: false,
    tag: 'info',
    aiReason: 'Your factory has a built shed area over 20,000 sq ft. Fire department must verify emergency gates, fire hydrants, and clear passage for fire trucks.',
    aiPoints: [
      'Submit building plan + fire hydrant layout to Fire Wing',
      'Minimum 2 fire extinguishers per 100 sq ft mandatory',
      'Emergency exit width must be at least 90 cm',
      'Provisional NOC valid during construction phase only',
    ],
    requiredDocs: ['Site Plan / Layout', 'Building Elevation Drawings', 'Fire Hydrant Layout'],
  },
  {
    id: 'appr-03',
    docName: 'Factory Building Plan Approval',
    authority: 'Town Planning & Municipal Corporation',
    fee: 20000,
    alreadyHave: false,
    uploadedFile: null,
    checkedForApply: false,
    tag: 'info',
    aiReason: 'Required because you are constructing an industrial shed. Municipal engineers must check structural stability and roadside open space norms.',
    aiPoints: [
      'Drawings must be signed by a Licensed Structural Engineer',
      'Submit FSI/FAR calculations with plot area certificate',
      'Open space setbacks (as per DP/TP rules) must be marked',
      'Online through Municipal Corporation portal or MIDC if in MIDC zone',
    ],
    requiredDocs: ['Site Plan / Layout', 'Structural Engineer Certificate', '7/12 Land Extract'],
  },
  {
    id: 'appr-04',
    docName: 'FSSAI State Manufacturing License',
    authority: 'Food Safety and Standards Authority of India',
    fee: 5000,
    alreadyHave: false,
    uploadedFile: null,
    checkedForApply: false,
    tag: 'info',
    aiReason: 'Since your planned business is Food Processing, a manufacturing license is required before selling food products in the market.',
    aiPoints: [
      'Apply on FoSCoS portal (foscos.fssai.gov.in)',
      'Hygienic layout plan, water test report, and pest control plan required',
      'State license covers turnover up to ₹20 Cr/year',
      'Valid for 1–5 years, renewable online',
    ],
    requiredDocs: ['Identity Proof (Aadhaar/PAN)', 'Water Quality Test Report', 'List of Machinery'],
  },
  {
    id: 'appr-05',
    docName: 'Factory Registration & License (Form 1)',
    authority: 'Directorate of Industrial Safety & Health (DISH)',
    fee: 4500,
    alreadyHave: false,
    uploadedFile: null,
    checkedForApply: false,
    tag: 'info',
    aiReason: 'Because you employ more than 10 workers using electrical power, DISH approval ensures working condition safety under the Factories Act, 1948.',
    aiPoints: [
      'Submit Form 1 to DISH before machinery energization',
      'Inspector will verify machine guarding, emergency stop systems',
      'License fee is based on number of workers and power load',
      'Must display license prominently inside the factory gate',
    ],
    requiredDocs: ['Identity Proof (Aadhaar/PAN)', 'List of Machinery', 'List of Directors/Partners'],
  },
];

export const userSystemVault = {
  'Identity Proof (Aadhaar/PAN)': 'Aadhaar_Card_Verified.pdf',
  '7/12 Land Extract': 'Land_Record_7_12.pdf',
};