export const performanceStats = {
  totalReceived: 120,
  signed: 90,
  rejected: 15,
  inspection: 10,
  delayed: 5,
  avgDaysToSign: 3,
};

export const historyRecords = [
  {
    id: 'DOC-2026-901',
    category: 'SIGNED',
    docName: 'Consent to Establish (CTE)',
    enterpriseName: 'Ganesh Agro Foods',
    owner: 'Ganesh Patil',
    dateSubmitted: '01 Sep 2026',
    dateActionTaken: '03 Sep 2026',
    timeTaken: '2 Days (On Time)',
    statusMessage: 'Signed and Issued',
    userDocs: ['Plot_Layout.pdf', 'Machine_Details.pdf'],
    officerRemarks: 'All water treatment plans are verified and correct.',
  },
  {
    id: 'DOC-2026-902',
    category: 'SIGNED',
    docName: 'Provisional Fire NOC',
    enterpriseName: 'Shivaji Metal Works',
    owner: 'Rahul Deshmukh',
    dateSubmitted: '02 Sep 2026',
    dateActionTaken: '05 Sep 2026',
    timeTaken: '3 Days (On Time)',
    statusMessage: 'Signed and Issued',
    userDocs: ['Fire_Safety_Plan.pdf', 'Building_Map.pdf'],
    officerRemarks: 'Emergency exits are well planned.',
  },
  {
    id: 'DOC-2026-903',
    category: 'SIGNED',
    docName: 'Factory Building Plan',
    enterpriseName: 'Jai Hind Textiles',
    owner: 'Amit Sharma',
    dateSubmitted: '25 Aug 2026',
    dateActionTaken: '02 Sep 2026',
    timeTaken: '8 Days (Delayed)',
    statusMessage: 'Signed with Delay',
    userDocs: ['Architect_Plan.pdf', '7_12_Extract.pdf'],
    officerRemarks: 'Delayed due to pending verification from city planner.',
  },
  {
    id: 'DOC-2026-904',
    category: 'REJECTED',
    docName: 'Hazardous Waste NOC',
    enterpriseName: 'Sai Chemicals Pvt Ltd',
    owner: 'Priya Kadam',
    dateSubmitted: '08 Sep 2026',
    dateActionTaken: '10 Sep 2026',
    timeTaken: '2 Days',
    statusMessage: 'Rejected by Officer',
    userDocs: ['Chemical_List.pdf', 'Waste_Plan.pdf'],
    officerRemarks: 'Missing details on how acid waste will be neutralized.',
  },
  {
    id: 'DOC-2026-905',
    category: 'INSPECTION',
    docName: 'Final Factory License',
    enterpriseName: 'Maharashtra Auto Parts',
    owner: 'Sanjay Verma',
    dateSubmitted: '10 Sep 2026',
    dateActionTaken: '11 Sep 2026',
    timeTaken: 'Scheduled',
    statusMessage: 'Inspection Set for 15 Sep 2026',
    userDocs: ['Machine_Setup.pdf', 'Worker_Safety_List.pdf'],
    officerRemarks: 'Officer will visit the site to check machine guards and safety.',
  },
];